/**
 * 用户可见文案集中管理（协议架构铁律 6）。
 * 逻辑代码里不得出现中文硬编码，一律从这里取。
 * 演示专用文案（场景描述、引导话术）在 src/demo/fixtures 与 src/demo/scenarios。
 */
export const COPY = {
  site: {
    name: '黑神话悟空 · 非官方粉丝互动站',
    shortName: '悟空同人站',
    tagline: '天命人自己的影神图、配装台与论坛',
    heroTitle: '黑神话悟空 · 粉丝互动站',
    heroEyebrow: '非官方粉丝作品',
    heroDescription:
      '影神图百科、配装模拟器、互动地图与天命人论坛——全部数据在本地浏览器模拟，随时可重置。',
  },

  disclaimer: {
    unofficial: '本站为非官方粉丝作品，与游戏科学（Game Science）及其关联方无隶属关系。',
    copyright:
      '《黑神话：悟空》的名称、角色、美术与音乐等版权归游戏科学所有，本站仅用于学习与交流。',
    mockData: '页面中的全部数据均由本地 Mock 生成，不代表任何真实信息。',
    spoiler: '默认隐藏剧透内容：剧情、结局与隐藏 Boss 相关信息需手动开启后才展示。',
  },

  nav: {
    home: '首页',
    news: '资讯',
    wiki: '影神图',
    guide: '攻略',
    map: '地图',
    buildLab: '配装',
    forum: '论坛',
    creation: '二创',
    event: '活动',
    shop: '灵蕴商城',
    user: '我的',
    admin: '后台',
    login: '登录',
  },

  navDescription: {
    home: '站点导览与主题令牌自检',
    news: '官方动态聚合，剧透内容自动遮罩',
    wiki: '影神图百科：妖王、人物与地点',
    guide: 'Boss、配装与结局攻略',
    map: '章节互动地图与收集点位',
    buildLab: '配装模拟器与属性实时计算',
    forum: '天命人交流版块',
    creation: '二创广场与授权标识',
    event: '赛季挑战与榜单',
    shop: '灵蕴商城与积分兑换',
    user: '个人主页与成长档案',
    admin: '演示后台：审核、看板与用户管理',
  },

  layout: {
    skipToContent: '跳到主要内容',
    openSidebar: '展开侧栏',
    collapseSidebar: '折叠侧栏',
    expandSidebar: '展开侧栏',
    themeLabel: '主题',
    spoilerLabel: '剧透内容',
    spoilerOn: '已显示',
    spoilerOff: '已隐藏',
    spoilerHint: '开启后展示剧情、结局与隐藏 Boss 信息',
    backToSite: '返回前台',
    adminArea: '演示后台',
    plannedSections: '规划中的后台模块',
    building: '建设中',
  },

  theme: {
    ink: '墨黑',
    paper: '宣纸',
    contrast: '高对比',
  },

  placeholder: {
    /** 阶段 0 统一占位文案：「{{页面名}} · 建设中」 */
    default: (pageName: string): string => `${pageName} · 建设中`,
    hint: '本页将在后续阶段交付，当前仅验证路由与布局骨架。',
  },

  common: {
    loading: '灵蕴汇聚中…',
    empty: '此处空空如也',
    error: '灵蕴紊乱，请稍后重试',
    retry: '重试',
    backHome: '返回首页',
    tokenCheck: '主题令牌自检',
    tokenCheckHint:
      '色块均绑定 CSS 变量令牌（tokens.css）；切换主题时整组应同步变化，说明没有硬编码色值漏网。',
    close: '关闭',
  },

  error: {
    unknown: '发生了未知错误',
    routeTitle: '此路不通',
    routeHint: '页面加载时出现异常，可返回首页重试。',
  },

  notFound: {
    title: '404 · 此页不在影神图中',
    hint: '你寻找的页面不存在，或已被妖怪吞了。',
  },

  forbidden: {
    title: '403 · 无资格入内',
    hint: '当前身份没有访问该区域的权限。可在演示控制台切换身份后重试。',
    currentRole: '当前身份',
  },

  /** 统一异步边界的默认槽位文案。 */
  boundary: {
    errorTitle: '灵蕴紊乱，数据没能取回来',
    offlineTitle: '网络已断开',
    offlineDescription:
      '演示控制台把界面状态切成了「断网」，所有请求都会立即失败。恢复后点重试即可。',
    emptyTitle: '此处空空如也',
    emptyDescription: '当前没有任何数据。可在演示控制台切换「填满数据」后再看。',
  },

  /** 破坏性操作统一二次确认（协议铁律 7）。 */
  confirm: {
    confirmText: '确认执行',
    cancelText: '取消',
    dangerHint: '该操作不可撤销',
  },

  /** 剧透遮罩：站级立场，影神图 / 资讯 / 论坛共用同一套文案。 */
  spoiler: {
    levels: {
      0: '无剧透',
      1: '含剧情信息',
      2: '含结局级信息',
    },
    reveal: '揭开这一条',
    revealed: '已揭开',
    title: '这条内容含剧透，默认遮罩',
    offNotice: '当前已开启剧透保护：含剧透内容需要手动揭开。',
    onNotice: '剧透保护已关闭：含剧透内容直接显示（可在顶栏切换）。',
  },

  /** 演示模式与控制台文案。 */
  demo: {
    banner: '演示模式 · 数据为本地模拟',
    bannerHint: '全部状态都在 URL 上，复制链接即可复现当前界面',
    enterDemo: '进入演示模式',
    exitDemo: '退出演示模式',
    consoleTitle: '演示控制台',
    openConsole: '打开演示控制台',
    closeConsole: '收起演示控制台',
    expandSection: '展开',
    collapseSection: '收起',
    linkCopied: '演示链接已复制，换台机器打开也是同一状态',
    linkCopyFailed: '复制失败，请手动复制地址栏链接',
    cleanMode: '截图模式',
    cleanHint: '隐藏控制台与顶部提示条，方便截图',
    section: {
      identity: '身份',
      uiState: '界面状态',
      theme: '主题',
      spoiler: '剧透',
      data: '数据',
      guide: '引导',
      scenario: '场景',
      tools: '工具',
    },
    sectionHint: {
      identity: '身份决定权限与可见内容，RequireRole 守卫读的就是它',
      uiState: '统一覆盖所有异步 UI，StateBoundary 优先服从它',
      theme: '三套主题共用一套设计令牌，切换即整体换肤',
      spoiler: '开启后展示剧情、结局与隐藏 Boss 信息',
      data: '数据保存在浏览器本地：IndexedDB + localStorage',
      guide: '分步引导会跨页跳转并高亮界面元素，支持 ← → 与 Esc',
      scenario: '一键切到某个典型演示现场',
      tools: '辅助调试与截图',
    },
    role: {
      guest: '访客',
      newbie: '新入天命人',
      active: '活跃天命人',
      moderator: '版主',
      admin: '管理员',
      banned: '封禁',
    },
    uiState: {
      normal: '正常',
      empty: '空数据',
      loading: '加载中',
      error: '错误',
      slow: '慢速网络',
      offline: '断网',
    },
    data: {
      reset: '重置',
      fill: '填满',
      clear: '清空',
      export: '导出快照',
      import: '导入快照',
      baselineHint: '首次进入会自动播种 12 条探针数据；快照可把本地库与 hmw: 存储一起备份。',
      resetConfirmTitle: '重置本地数据？',
      resetConfirmDescription: '会清空本地库并写回基线种子数据（12 条探针）。',
      fillConfirmTitle: '填充演示数据？',
      fillConfirmDescription: '会清空本地库并写入 60 条探针数据，用于验证长列表。',
      clearConfirmTitle: '清空全部本地数据？',
      clearConfirmDescription:
        '本地库与所有 hmw: 开头的本地存储都会被清空，包括影神图词条等演示内容、主题、侧栏偏好与勾选记录。',
      seeded: (count: number): string => `已写入 ${count} 条演示数据`,
      cleared: '本地数据已清空',
      exported: '快照已开始下载（JSON）',
      imported: (rows: number, keys: number): string =>
        `快照导入完成：${rows} 条数据库记录、${keys} 个本地存储键已还原`,
      importFailed: '快照文件无法解析或版本不兼容',
      importEmpty: '没有选择文件',
    },
    scenario: {
      label: '预设场景',
      apply: '应用场景',
      applied: (name: string): string => `已切到场景：${name}`,
      unknown: '未找到该场景',
    },
    tour: {
      label: '引导剧本',
      start: '启动引导',
      unknown: '未找到该引导剧本',
      next: '下一步',
      previous: '上一步',
      done: '完成',
      close: '退出引导',
      progress: '第 {{current}} / {{total}} 步',
      missingElement: '这一步的目标元素没出现，已跳过高亮',
    },
    tools: {
      grid: '布局栅格',
      outline: '组件边界',
      perf: '性能面板',
      record: '操作记录',
      copyLink: '复制演示链接',
    },
    record: {
      enabled: '正在记录操作路径（record=1）',
      count: (count: number): string => `已记录 ${count} 条`,
      export: '导出记录',
      clear: '清空记录',
      exported: '操作记录已下载（JSON）',
      cleared: '操作记录已清空',
    },
    externalLinkBlocked: (url: string): string => `演示模式已拦截外链跳转：${url}`,
    spoilerOn: '剧透内容已显示',
    spoilerOff: '剧透内容已隐藏',
  },

  /** 演示探针自检面板文案。 */
  probe: {
    title: '演示系统自检 · 探针列表',
    description:
      '这一块是阶段 1 的自检面板：它真实走「Repository → MSW → IndexedDB」链路，用来验证加载 / 空 / 错误 / 断网 / 慢速五种状态，以及写操作持久化与快照备份。阶段 2 起会被真实业务列表取代。',
    countLabel: (total: number): string => `共 ${total} 条探针`,
    toggle: (label: string, collected: boolean): string =>
      `${collected ? '取消勾选' : '勾选'} ${label}`,
    collected: '已勾选',
    notCollected: '未勾选',
    updateFailed: '勾选失败，请重试',
    updateDone: '已更新勾选状态',
  },

  /** 性能面板文案（工具分区）。 */
  perf: {
    title: '性能面板',
    fps: '帧率',
    domNodes: 'DOM 节点',
    queryCache: 'Query 缓存',
    heap: 'JS 堆',
    unavailable: '不可用',
  },

  /** 登录态在顶栏的呈现。 */
  session: {
    entry: '登录',
    resolving: '正在确认登录状态…',
    logout: '退出登录',
    logoutDone: '已退出登录',
    spiritPoints: (points: number): string => `${points} 灵蕴`,
    openProfile: (name: string): string => `打开 ${name} 的成长中心`,
  },

  /** 注册 / 登录页。 */
  auth: {
    title: '天命人身份',
    description:
      '登录后可以上香签到、领取任务、收取消息。演示站没有真实账号体系，一切数据都留在你自己的浏览器里。',
    loginTab: '登录',
    registerTab: '注册',
    username: '用户名',
    displayName: '道号',
    password: '密码',
    passwordConfirm: '确认密码',
    usernamePlaceholder: '3–16 位字母、数字或下划线',
    displayNamePlaceholder: '1–12 个字符，会显示在名片上',
    passwordPlaceholder: '6–32 位',
    loginAction: '登录并进入',
    registerAction: '注册并进入',
    demoLogin: '一键登录演示账号',
    demoHint: (username: string, password: string): string =>
      `演示账号：${username} / ${password}（也可以直接一键登录）`,
    loginSuccess: (name: string): string => `欢迎回来，${name}`,
    registerSuccess: (name: string): string => `注册成功，欢迎 ${name}`,
    demoLoginSuccess: (name: string): string => `已用演示账号登录：${name}`,
    alreadyLoggedIn: '你已经登录了',
    toGrowthCenter: '进入成长中心',
    needLoginTitle: '尚未登录',
    needLoginDescription: '成长中心需要天命人身份：登录或注册后即可上香、领任务、收消息。',
    toLogin: '去登录',
    bannedTitle: '账号处于封禁状态',
    bannedDescription: '封禁身份无法上香与领取任务。可在演示控制台把身份切回「活跃天命人」再试。',
  },

  /** 成长中心：签到 / 任务 / 消息 / 境界。 */
  growth: {
    title: '成长中心',
    description: '签到、任务、消息都在这一页，数据全部保存在浏览器本地（IndexedDB）。',
    checkIn: {
      title: '土地庙上香',
      action: '上香',
      done: '今日已上香',
      submitting: '上香中…',
      streak: (days: number): string => `连续 ${days} 天`,
      total: (days: number): string => `累计 ${days} 天`,
      rewardPreview: (points: number): string => `今日可得 ${points} 灵蕴`,
      calendarTitle: '近 30 天',
      checkedHint: '已上香',
      uncheckedHint: '未上香',
      todayHint: '今天',
      success: (points: number, streak: number): string =>
        `上香完成：+${points} 灵蕴，连续 ${streak} 天`,
    },
    tasks: {
      title: '任务中心',
      daily: '每日',
      weekly: '周常',
      hidden: '隐藏成就',
      claim: '领取',
      claimed: '已领取',
      claimable: '可领取',
      progress: (progress: number, target: number): string => `${progress} / ${target}`,
      reward: (points: number): string => `+${points} 灵蕴`,
      expires: (date: string): string => `${date} 截止`,
      empty: '这一类暂时没有任务',
      claimSuccess: (title: string, points: number): string =>
        `已领取「${title}」：+${points} 灵蕴`,
      claimFailed: '领取失败',
      hiddenHint: '隐藏成就需要自己发现，进度不会提前剧透。',
    },
    notifications: {
      title: '消息中心',
      all: '全部',
      unreadOnly: '仅未读',
      markAllRead: '全部已读',
      markRead: '标为已读',
      unread: (count: number): string => `${count} 条未读`,
      empty: '暂时没有消息',
      emptyUnread: '没有未读消息',
      allReadDone: (count: number): string => `已把 ${count} 条消息标为已读`,
      category: {
        system: '系统',
        achievement: '成就',
        reply: '回复',
        like: '点赞',
        follow: '关注',
      },
      openLink: '前往查看',
      readFailed: '标记已读失败',
    },
    level: {
      label: '修行境界',
      exp: '修为',
      expValue: (exp: number): string => `${exp} 修为`,
      level: (level: number): string => `第 ${level} 境`,
      toNext: (exp: number): string => `距下一境界还需 ${exp} 修为`,
      maxed: '已至最高境界',
    },
    badges: {
      title: '成就徽章',
      unlockedRatio: (unlocked: number, total: number): string => `${unlocked} / ${total} 已解锁`,
      locked: '未解锁',
      unlockedAt: (date: string): string => `${date} 解锁`,
      lockedBadgeHint: '未解锁的徽章只显示名字与来历，具体条件留给你自己摸索。',
    },
    stats: {
      spiritPoints: '灵蕴',
      badges: '徽章',
      streak: '连续上香',
      days: (days: number): string => `${days} 天`,
    },
    profile: {
      title: '天命人名片',
      titleLabel: '称号',
      joinedAt: (date: string): string => `${date} 入山`,
    },
  },

  /** 影神图百科（阶段 2 模块二）。 */
  wiki: {
    title: '影神图',
    description:
      '妖王、人物、妖怪与地点的档案。筛选与搜索都会写进 URL，可以直接把某一组筛选结果分享出去。',
    searchLabel: '搜索词条',
    searchPlaceholder: '名称、别名或拼音首字母（如 hfs = 黑风山）',
    searchHint: '支持全拼、首字母与别名',
    filterChapter: '章节',
    filterCategory: '类型',
    filterRarity: '稀有度',
    sortLabel: '排序',
    all: '全部',
    chapterLabel: (chapter: number, name: string): string => `第${chapter}章 · ${name}`,
    category: {
      yaoguai: '妖怪',
      npc: '人物',
      boss: '妖王',
      location: '地点',
    },
    rarityLabel: (rarity: number): string => `${rarity} 星`,
    sort: {
      relevance: '相关度',
      rarity: '稀有度',
      chapter: '章节',
      name: '名称',
    },
    resultCount: (count: number): string => `共 ${count} 条词条`,
    resultCountFiltered: (matched: number, total: number): string => `${matched} / ${total} 条词条`,
    empty: '没有符合条件的词条',
    emptyHint: '试试清空筛选，或换一个关键词。',
    resetFilters: '清空筛选',
    spoilerHidden: '当前已隐藏含剧透的词条；可在顶栏或演示控制台开启。',
    spoilerVisible: '含剧透的词条已显示。',
    favorite: {
      add: '收藏',
      remove: '取消收藏',
      added: (name: string): string => `已收藏：${name}`,
      removed: (name: string): string => `已取消收藏：${name}`,
      failed: '收藏操作失败',
    },
    compare: {
      title: '词条对比',
      add: '加入对比',
      remove: '移出对比',
      limitHint: (limit: number): string => `最多同时对比 ${limit} 条`,
      full: (limit: number): string => `最多对比 ${limit} 条，先移出一条再添加`,
      clear: '清空',
      empty: '从卡片上的「加入对比」挑 2–3 条词条，这里会并列展示它们的属性。',
      field: {
        category: '类型',
        chapter: '章节',
        rarity: '稀有度',
        alias: '别名',
        drops: '掉落',
        related: '关联词条',
        spoiler: '剧透级别',
        description: '简介',
      },
      none: '—',
    },
    detail: {
      open: '查看详情',
      close: '关闭详情',
      alias: '别名',
      drops: '掉落',
      related: '关联词条',
      relatedCount: (count: number): string => `${count} 条关联`,
      graphTitle: '关联图谱',
      graphHint: '拖动节点可调整布局，滚轮缩放；点击节点切换中心词条。',
      graphLoading: '图谱加载中…',
      graphEmpty: '这条词条暂时没有关联数据。',
      missing: '词条不存在，可能已被「清空数据」移除。',
    },
  },

  /** 资讯（阶段 2 模块三）。 */
  news: {
    title: '资讯',
    description: '聚合官方渠道动态与本站编辑内容；含剧透的条目默认遮罩，点开才看。',
    demoNotice: '本页为演示数据，不代表任何官方信息；来源按钮指向真实渠道首页。',
    searchLabel: '搜索资讯',
    searchPlaceholder: '标题、摘要、来源或标签',
    filterCategory: '类目',
    filterTag: '标签',
    sortLabel: '排序',
    sort: {
      latest: '最新在前',
      oldest: '最早在前',
    },
    all: '全部',
    category: {
      official: '官方',
      update: '版本',
      event: '活动',
      media: '影像',
      community: '社区',
    },
    tag: {
      version: '版本更新',
      balance: '平衡性',
      dlc: '后续内容',
      art: '美术',
      music: '音乐',
      interview: '访谈',
      esports: '赛事',
      merch: '周边',
      guide: '攻略',
      community: '社区',
    },
    sourceKind: {
      official: '官方渠道',
      media: '媒体渠道',
      community: '社区渠道',
      editorial: '本站编辑',
    },
    resultCount: (count: number): string => `${count} 条资讯`,
    resultCountFiltered: (matched: number, total: number): string => `${matched} / ${total} 条资讯`,
    empty: '没有符合条件的资讯',
    emptyHint: '试试清空筛选，或换一个关键词。',
    resetFilters: '清空筛选',
    pinned: '置顶',
    expand: '展开正文',
    collapse: '收起正文',
    openSource: '查看来源',
    noSource: '本站编辑内容，没有外部来源',
    maskedNotice: (count: number): string => `其中 ${count} 条含剧透，已遮罩`,
    timelineToday: '今天',
    timelineYesterday: '昨天',
  },
} as const;
